name: code_generators
description: A sample command-line application.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build: any
  path: any
  markdown: any

dev_dependencies:
  build_config: any
  build_runner: any
  pedantic: any
  test: any
